@url=http://localhost:3000/web/api
@json=Content-Type: application/json
### 所有用戶
get {{url}}/users

### 註冊
post {{url}}/register
{{json}}

{
  "username":"leohuo",
  "password":"111111"
}

### 登入
post {{url}}/login
{{json}}

{
  "username":"leohuo",
  "password":"111111"
}

### 輪播圖
get {{url}}/ads/list
{{json}}